/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bai5;

/**
 *
 * @author 1000l
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Bai5 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Bai5.class.getName());

    /**
     * Creates new form Bai5
     */
    public Bai5(){
        setTitle("Bai 5: Dang ky");
        setSize(400, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new GridLayout(6, 1));

        JTextField txtTen = new JTextField();
        JPasswordField txtPass = new JPasswordField();
        JRadioButton rbNam = new JRadioButton("Nam");
        JRadioButton rbNu = new JRadioButton("Nu");
        ButtonGroup bg = new ButtonGroup(); bg.add(rbNam); bg.add(rbNu);
        JCheckBox cbDocSach = new JCheckBox("Doc sach");
        JCheckBox cbDuLich = new JCheckBox("Du lich");

        add(new JLabel("Ho ten:")); add(txtTen);
        add(new JLabel("Mat khau:")); add(txtPass);
        
        JPanel pGender = new JPanel(); pGender.add(rbNam); pGender.add(rbNu);
        add(new JLabel("Gioi tinh:")); add(pGender);

        JPanel pHobby = new JPanel(); pHobby.add(cbDocSach); pHobby.add(cbDuLich);
        add(new JLabel("So thich:")); add(pHobby);

        JButton btnDangKy = new JButton("Dang ky");
        add(btnDangKy);

        JTextArea txtOutput = new JTextArea();
        add(new JScrollPane(txtOutput));

        btnDangKy.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String kq = "Ho ten: " + txtTen.getText() + "\n";
                kq += "Gioi tinh: " + (rbNam.isSelected() ? "Nam" : "Nu") + "\n";
                kq += "So thich: " + (cbDocSach.isSelected() ? "Doc sach " : "") 
                                    + (cbDuLich.isSelected() ? "Du lich" : "");
                txtOutput.setText(kq);
            }
        });

        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new Bai5();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
