/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bai3;

/**
 *
 * @author 1000l
 */
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;

public class Bai3 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Bai3.class.getName());

    /**
     * Creates new form Bai3
     */
    public Bai3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        JFrame frame = new JFrame("Tran Gia Luong - TT601-K14");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(500, 500);
        frame.setLocationRelativeTo(null);
        frame.setLayout(new GridLayout(3, 1)); 
        
        JPanel row1 = new JPanel(new FlowLayout(FlowLayout.LEFT, 20, 20));
        JPanel p1 = new JPanel();
        p1.setPreferredSize(new Dimension(100, 100));
        p1.setBackground(new Color(204, 255, 255));
        p1.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED)); 
        row1.add(p1);
        frame.add(row1);

        JPanel row2 = new JPanel(new FlowLayout(FlowLayout.CENTER, 20, 20));
        
        JPanel p2 = new JPanel();
        p2.setPreferredSize(new Dimension(100, 100));
        p2.setBackground(new Color(204, 255, 204)); 
        p2.setBorder(BorderFactory.createEtchedBorder()); 
        
        JPanel p3 = new JPanel();
        p3.setPreferredSize(new Dimension(100, 100));
        p3.setBackground(new Color(204, 204, 255)); 
        p3.setBorder(BorderFactory.createLineBorder(Color.BLACK)); 
        
        row2.add(p2);
        row2.add(p3);
        frame.add(row2);

        JPanel row3 = new JPanel(new FlowLayout(FlowLayout.CENTER, 20, 20));
        
        JPanel p4 = new JPanel();
        p4.setPreferredSize(new Dimension(100, 100));
        p4.setBackground(new Color(255, 102, 102)); 
        p4.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, Color.RED));
        
        JPanel p5 = new JPanel();
        p5.setPreferredSize(new Dimension(100, 100));
        p5.setBackground(Color.YELLOW);
        p5.setBorder(new SoftBevelBorder(BevelBorder.RAISED)); 
        
        JPanel p6 = new JPanel();
        p6.setPreferredSize(new Dimension(100, 100));
        p6.setBackground(new Color(0, 255, 204)); 
        p6.setBorder(BorderFactory.createTitledBorder("Title")); 
        
        row3.add(p4);
        row3.add(p5);
        row3.add(p6);
        frame.add(row3);

        frame.setVisible(true);
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

