/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bai2;

/**
 *
 * @author 1000l
 */
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;

public class Bai2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Bai2.class.getName());

    /**
     * Creates new form Bai2
     */
    public Bai2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        JFrame frame = new JFrame("Tran Gia Luong - TT601-K14");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(600, 500);
        frame.setLocationRelativeTo(null);
        frame.setLayout(new BorderLayout(10, 10)); 

        JPanel pTop = new JPanel(new GridLayout(1, 4, 10, 10));
        pTop.setPreferredSize(new Dimension(0, 120));

        JPanel p1 = new JPanel(); p1.setBackground(new Color(255, 255, 102)); 
        JPanel p2 = new JPanel(); p2.setBackground(new Color(255, 102, 153)); 
        JPanel p3 = new JPanel(); p3.setBackground(new Color(0, 128, 128));   
        JPanel p4 = new JPanel(); p4.setBackground(new Color(10, 40, 40));   
        
        pTop.add(p1); pTop.add(p2); pTop.add(p3); pTop.add(p4);
        frame.add(pTop, BorderLayout.NORTH);

        JPanel pCenter = new JPanel(new GridLayout(1, 2, 10, 10)); 
        
        JPanel p5 = new JPanel(); p5.setBackground(Color.GREEN); 
        JPanel p6 = new JPanel(); p6.setBackground(new Color(204, 0, 51)); 
        
        pCenter.add(p5);
        pCenter.add(p6);
        frame.add(pCenter, BorderLayout.CENTER);

        JPanel pBottom = new JPanel();
        pBottom.setBackground(new Color(0, 102, 255)); 
        pBottom.setPreferredSize(new Dimension(0, 100)); 
        
        frame.add(pBottom, BorderLayout.SOUTH);

        frame.setVisible(true);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

