/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bai3;

/**
 *
 * @author 1000l
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Bai3 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Bai3.class.getName());

    /**
     * Creates new form Bai3
     */
    public Bai3() {
        setTitle("Bai 3: So thich");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new FlowLayout());

        JCheckBox cb1 = new JCheckBox("Doc sach");
        JCheckBox cb2 = new JCheckBox("Nghe nhac");
        JCheckBox cb3 = new JCheckBox("Xem phim");
        JCheckBox cb4 = new JCheckBox("Du lich");

        add(cb1); add(cb2); add(cb3); add(cb4);

        JButton btnXacNhan = new JButton("Xac nhan");
        add(btnXacNhan);

        JTextArea txtKetQua = new JTextArea(5, 30);
        add(new JScrollPane(txtKetQua));

        btnXacNhan.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String s = "So thich da chon:\n";
                if(cb1.isSelected()) s += "- Doc sach\n";
                if(cb2.isSelected()) s += "- Nghe nhac\n";
                if(cb3.isSelected()) s += "- Xem phim\n";
                if(cb4.isSelected()) s += "- Du lich\n";
                txtKetQua.setText(s);
            }
        });

        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new Bai3();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
